name: Deploy agent Os Instance

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Build Agent Binaries - Windows amd64
        run: |
          cd cmd/agent
          GOOS=windows GOARCH=amd64 go build -o agent-windows-amd64.exe main.go
          echo "Built agent binary:"
          ls -la agent-windows-amd64.exe
      
      - name: Build Agent Binaries - Linux amd64 and arm64
        run: |
          cd cmd/agent
          GOOS=linux GOARCH=arm64 go build -o agent-linux-arm64 main.go
          GOOS=linux GOARCH=amd64 go build -o agent-linux-amd64 main.go
      
      - name: Build Agent Binaries - macOS amd64 and arm64
        run: |
          cd cmd/agent
          GOOS=darwin GOARCH=arm64 go build -o agent-macos-arm64 main.go
          GOOS=darwin GOARCH=amd64 go build -o agent-macos-amd64 main.go

      - name: Build Manager Binaries - Windows amd64
        run: |
          cd cmd/manager
          GOOS=windows GOARCH=amd64 go build -o manager-windows-amd64.exe main.go
          echo "Built manager binary:"
          ls -la manager-windows-amd64.exe
      
      - name: Build Manager Binaries - Linux amd64 and arm64
        run: |
          cd cmd/manager
          GOOS=linux GOARCH=arm64 go build -o manager-linux-arm64 main.go
          GOOS=linux GOARCH=amd64 go build -o manager-linux-amd64 main.go

      - name: Build Manager Binaries - macOS amd64 and arm64
        run: |
          cd cmd/manager
          GOOS=darwin GOARCH=arm64 go build -o manager-macos-arm64 main.go
          GOOS=darwin GOARCH=amd64 go build -o manager-macos-amd64 main.go

      - name: Build Updater Binaries - Windows amd64
        run: |
          cd cmd/updater
          GOOS=windows GOARCH=amd64 go build -o updater-windows-amd64.exe main.go

      - name: Build Updater Binaries - Linux amd64 and arm64
        run: |
          cd cmd/updater
          GOOS=linux GOARCH=arm64 go build -o updater-linux-arm64 main.go
          GOOS=linux GOARCH=amd64 go build -o updater-linux-amd64 main.go

      - name: Build Updater Binaries - macOS amd64 and arm64
        run: |
          cd cmd/updater
          GOOS=darwin GOARCH=arm64 go build -o updater-macos-arm64 main.go
          GOOS=darwin GOARCH=amd64 go build -o updater-macos-amd64 main.go

      - name: List built binaries
        run: |
          echo "=== Agent binaries ==="
          ls -la cmd/agent/agent-*
          echo "=== Manager binaries ==="
          ls -la cmd/manager/manager-*
          echo "=== Updater binaries ==="
          ls -la cmd/updater/updater-*

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            cmd/agent/agent-*
            cmd/manager/manager-*
            cmd/updater/updater-*

  build-windows-installers:
    runs-on: windows-latest
    needs: build-binaries
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: binaries/

      - name: Setup WiX Toolset
        run: |
          # Install WiX Toolset via Chocolatey
          choco install wixtoolset
          # Add WiX to PATH (if needed)
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Prepare Windows Binaries
        run: |
          # Debug: List what was downloaded
          echo "=== Debug: Contents of binaries directory ==="
          Get-ChildItem -Recurse binaries/
          
          # Check if installers directory exists
          if (!(Test-Path "installers")) {
            echo "ERROR: installers directory not found!"
            exit 1
          }
          
          # Enter installers directory
          cd installers
          
          # Copy the manager and agent binaries from the correct paths
          # Based on the artifact structure, they are in binaries/manager/ and binaries/agent/
          $managerPath = "..\binaries\manager\manager-windows-amd64.exe"
          $agentPath = "..\binaries\agent\agent-windows-amd64.exe"
          
          # Check if manager binary exists
          if (Test-Path $managerPath) {
            copy $managerPath manager.exe
            echo "Copied manager binary from $managerPath"
          } else {
            echo "ERROR: Manager binary not found at $managerPath"
            echo "=== Available files in binaries/manager/ ==="
            Get-ChildItem "..\binaries\manager\" -ErrorAction SilentlyContinue
            exit 1
          }
          
          # Check if agent binary exists
          if (Test-Path $agentPath) {
            copy $agentPath agent.exe  
            echo "Copied agent binary from $agentPath"
          } else {
            echo "ERROR: Agent binary not found at $agentPath"
            echo "=== Available files in binaries/agent/ ==="
            Get-ChildItem "..\binaries\agent\" -ErrorAction SilentlyContinue
            exit 1
          }
          
          # Build config executables needed by WiX
          echo "=== Building config executables ==="
          
          # Build manager config executable
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          go build -o config_manager.exe manager/install_manager_windows.go
          echo "Built config_manager.exe"
          
          # Build agent config executable  
          $env:SCM = "agent"
          go build -o config_agent.exe agent/install_agent_windows.go
          echo "Built config_agent.exe"
          
          # List files to verify
          echo "=== Files in installers directory ==="
          dir

      - name: Build Windows Installers
        run: |
          # Enter installers directory
          cd installers
          
          # Build Manager MSI
          # Use candle.exe to compile manager XML to wixobj
          candle.exe install_manager_windows.xml -o install_manager_windows.wixobj
          # Use light.exe with WixUIExtension to create MSI
          light.exe -ext WixUIExtension install_manager_windows.wixobj -o install_manager_windows.msi
          
          # Build Agent MSI  
          # Use candle.exe to compile agent XML to wixobj
          candle.exe install_agent_windows.xml -o install_agent_windows.wixobj
          # Use light.exe with WixUIExtension to create MSI
          light.exe -ext WixUIExtension install_agent_windows.wixobj -o install_agent_windows.msi
          
          # List generated files
          dir *.msi

      - name: Upload Windows Installers
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: |
            installers/*.msi

  organize-and-release:
    runs-on: ubuntu-latest
    needs: [build-binaries, build-windows-installers]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: binaries/

      - name: Download Windows Installers
        uses: actions/download-artifact@v4
        with:
          name: windows-installers
          path: windows-installers/

      - name: Organize Release Assets
        run: |
          # Create directories for organized release
          mkdir -p release/manager
          mkdir -p release/agent
          mkdir -p release/updater
          mkdir -p release/installer
          
          # Copy manager binaries with organized structure
          cp binaries/manager/manager-windows-amd64.exe release/manager/
          cp binaries/manager/manager-linux-amd64 release/manager/
          cp binaries/manager/manager-linux-arm64 release/manager/
          cp binaries/manager/manager-macos-amd64 release/manager/
          cp binaries/manager/manager-macos-arm64 release/manager/
          
          # Copy agent binaries with organized structure
          cp binaries/agent/agent-windows-amd64.exe release/agent/
          cp binaries/agent/agent-linux-amd64 release/agent/
          cp binaries/agent/agent-linux-arm64 release/agent/
          cp binaries/agent/agent-macos-amd64 release/agent/
          cp binaries/agent/agent-macos-arm64 release/agent/

          # Copy updater binaries with organized structure
          cp binaries/updater/updater-windows-amd64.exe release/updater/
          cp binaries/updater/updater-linux-amd64 release/updater/
          cp binaries/updater/updater-linux-arm64 release/updater/
          cp binaries/updater/updater-macos-arm64 release/updater/
          cp binaries/updater/updater-macos-amd64 release/updater/

          # Copy manager installers linux
          cp installers/install_manager_linux.sh release/installer/
          cp installers/uninstall_manager_linux.sh release/installer/

          # Copy manager installers macos
          cp installers/install_manager_macos.sh release/installer/
          cp installers/uninstall_manager_macos.sh release/installer/

          # Copy agent installers linux
          cp installers/install_agent_linux.sh release/installer/
          cp installers/uninstall_agent_linux.sh release/installer/

          # Copy agent installers macos
          cp installers/install_agent_macos.sh release/installer/
          cp installers/uninstall_agent_macos.sh release/installer/

          # Copy updater installers linux
          cp installers/install_updater_linux.sh release/installer/
          cp installers/uninstall_updater_linux.sh release/installer/

          # Copy updater installers macos
          cp installers/install_updater_macos.sh release/installer/
          cp installers/uninstall_updater_macos.sh release/installer/

          # Copy Windows installers
          cp windows-installers/*.msi release/installer/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/manager/manager-windows-amd64.exe
            release/manager/manager-linux-amd64
            release/manager/manager-linux-arm64
            release/manager/manager-macos-amd64
            release/manager/manager-macos-arm64
            release/agent/agent-windows-amd64.exe
            release/agent/agent-linux-amd64
            release/agent/agent-linux-arm64
            release/agent/agent-macos-amd64
            release/agent/agent-macos-arm64
            release/updater/updater-windows-amd64.exe
            release/updater/updater-linux-amd64
            release/updater/updater-linux-arm64
            release/updater/updater-macos-amd64
            release/updater/updater-macos-arm64
            release/installer/install_manager_linux.sh
            release/installer/uninstall_manager_linux.sh
            release/installer/install_manager_macos.sh
            release/installer/uninstall_manager_macos.sh
            release/installer/install_agent_linux.sh
            release/installer/uninstall_agent_linux.sh
            release/installer/install_agent_macos.sh
            release/installer/uninstall_agent_macos.sh
            release/installer/install_updater_linux.sh
            release/installer/uninstall_updater_linux.sh
            release/installer/install_updater_macos.sh
            release/installer/uninstall_updater_macos.sh
            release/installer/install_manager_windows.msi
            release/installer/install_agent_windows.msi
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false